// Generated by Xata Codegen 0.28.2. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "TestEvents",
    columns: [
      { name: "month", type: "int" },
      { name: "day", type: "int" },
      { name: "name", type: "string" },
      { name: "image_url", type: "string" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type TestEvents = InferredTypes["TestEvents"];
export type TestEventsRecord = TestEvents & XataRecord;

export type DatabaseSchema = {
  TestEvents: TestEventsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Info-OIAC-s-workspace-adropt.us-west-2.xata.sh/db/oiacedmonton",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
