// Generated by Xata Codegen 0.28.2. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "TestEvents",
    columns: [
      { name: "month", type: "int" },
      { name: "day", type: "int" },
      { name: "name", type: "string" },
      { name: "image_url", type: "string" },
    ],
  },
  {
    name: "Volunteers",
    columns: [
      { name: "name", type: "string" },
      { name: "email", type: "string" },
      { name: "phone", type: "string" },
      { name: "expertise", type: "string" },
      { name: "message", type: "text" },
      { name: "createdAt", type: "datetime" },
    ],
  },
  {
    name: "UtmHits",
    columns: [
      { name: "source", type: "string" },
      { name: "timestamp", type: "datetime" },
      { name: "donateButtonClicked", type: "bool" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type TestEvents = InferredTypes["TestEvents"];
export type TestEventsRecord = TestEvents & XataRecord;

export type Volunteers = InferredTypes["Volunteers"];
export type VolunteersRecord = Volunteers & XataRecord;

export type UtmHits = InferredTypes["UtmHits"];
export type UtmHitsRecord = UtmHits & XataRecord;

export type DatabaseSchema = {
  TestEvents: TestEventsRecord;
  Volunteers: VolunteersRecord;
  UtmHits: UtmHitsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Info-OIAC-s-workspace-adropt.us-west-2.xata.sh/db/oiacedmonton",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
